export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";

export const SINGLE_PRODUCT_FAIL="SINGLE_PRODUCT_FAIL";
export const SINGLE_PRODUCT_SUCCESS="SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_REQUEST="SINGLE_PRODUCT_REQUEST";

export const EMPTY_FAIL="EMPTY_FAIL";
export const EMPTY_SUCCESS="EMPTY_SUCCESS";
export const EMPTY_REQUEST="EMPTY_REQUEST";

export const ADD_FAIL= "ADD_FAIL";
export const ADD_SUCCESS= "ADD_SUCCESS";
export const ADD_REQUEST= "ADD_REQUEST";

export const ALL_CATAGORY_REQUEST= "ALL_CATAGORY_REQUEST";
export const ALL_CATAGORY_SUCCESS= "ALL_CATAGORY_SUCCESS";
export const ALL_CATAGORY_FAIL= "ALL_CATAGORY_FAIL";

export const SINGLE_VENDOR_FAIL="SINGLE_VENDOR_FAIL";
export const SINGLE_VENDOR_SUCCESS="SINGLE_VENDOR_SUCCESS";
export const SINGLE_VENDOR_REQUEST="SINGLE_VENDOR_REQUEST";

export const LARGEST_SOLD_REQUEST= "LARGEST_SOLD_REQUEST";
export const LARGEST_SOLD_SUCCESS= "LARGEST_SOLD_SUCCESS";
export const LARGEST_SOLD_FAIL= "LARGEST_SOLD_FAIL";

export const ALL_VENDOR_REQUEST= "ALL_VENDOR_REQUEST";
export const ALL_VENDOR_SUCCESS= "ALL_VENDOR_SUCCESS";
export const ALL_VENDOR_FAIL= "ALL_VENDOR_FAIL";

export const UPDATE_PAYMENTS_REQUEST= "UPDATE_PAYMENTS_REQUEST";
export const UPDATE_PAYMENTS_SUCCESS= "UPDATE_PAYMENTS_SUCCESS";
export const UPDATE_PAYMENTS_FAIL= "UPDATE_PAYMENTS_FAIL";

export const CREATE_PRODUCT_REQUEST= "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS= "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL= "CREATE_PRODUCT_FAIL";

export const EDIT_PRODUCT_REQUEST= "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS= "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL= "EDIT_PRODUCT_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";